story3/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

app_name="story3"

urlpatterns = [
    path('', views.homeView, name="homepage"),
    path('projects/', views.projectView, name="projects")
]

storyPPW/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
]

story3/models.py
from django.db import models

# Create your models here.

story3/views.py
from django.shortcuts import render

def homeView(request):
    return render(request,'story3/homepage.html')

def projectView(request):
    return render(request, 'story3/my-projects.html')

story3/templates/story3/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
{% load static %}

<body data-spy="scroll" data-target=".navbar" data-offset=100>

    <div class="big-box" id="homepage">
        <!-- intro section -->
        <div class="flex-container row-style skyblue" id="intro">
            <div class="flex-container column-style" id=intro-left>
                <span class="title">Hi there,</span>
                <span class="title">I am 
                    <span id="name">Christopher Yohanes Hasian Tamba</span>
                </span>
                <span class="title">Glad to meet you all!</span>
            </div>
            <div class="flex-container column-style" id="intro-right">
                <a href="https://drive.google.com/file/d/1ldGsKBjX4maRtzPBP9Suv_evGV1GZu0y/view?usp=sharing" 
                    class="tombol button-text" id="my-resume" target="_blank">
                    My Resume
                </a>
                <a href="#about" class="tombol button-text" id="explore">
                    About me!
                </a>
            </div>
        </div>

        <!-- div for about page -->
        <div class="flex-container column-style" id="about">
            <div class="flex-container" id="about-title">
                <span class="title">About Me</span>
            </div>
            <div class="flex-container" id="data">
                <div class="" id="about-left">
                    <img src="{% static 'img/foto.png' %}" alt="profile image" id="profile-img">
                </div>
                <div class="flex-container column-style" id= "about-right">
                    <span class="subtitle">
                        My name is Christopher Yohanes Hasian Tamba and you can call me 
                        <span class="blue-txt">Christo</span>
                    </span>
                    <span class="subtitle">
                        I'm currently an 
                        <span class="bold-txt">Information System</span>
                        student at 
                        <span class="bold-txt">University of Indonesia</span>
                    </span>
                    <span class="subtitle">
                        I love to study 
                        <span class="violet-txt">technology</span>
                        and how it works to make a great impact in  
                        <span class="violet-txt">business</span>.
                    </span>
                </div>
            </div>
        </div>

        <!-- section for skills -->
        <div class="flex-container column-style skyblue" id="skills">
            <div class="" id="skill-title">
                <span class="title">My Skills</span>
            </div>
            <div class="flex-container row-style" id="skill-sub">
                <div class="flex-container column-style" id="tech">
                    <span class="subtitle blue-txt miring title-sub">
                            Technical Skills
                    </span>
                    <span class="body-txt">Python</span>
                    <span class="skyblue-txt body-txt">Java</span>
                    <span class="body-txt">Wordpress</span>
                    <span class="skyblue-txt body-txt">HTML 5</span>
                    <span class="body-txt">CSS</span>
                    <span class="skyblue-txt body-txt">Django</span>
                </div>
                <div class="flex-container column-style" id="personal">
                    <span class="subtitle blue-txt miring title-sub">
                            Personal Skills
                    </span>
                    <span class="body-txt">The ability to learn and follow</span>
                    <span class="body-txt">instructions</span>
                    <span class="skyblue-txt body-txt">Discipline, hardworking, and </span>
                    <span class="skyblue-txt body-txt">trustworthy person</span>
                    <span class="body-txt">Good time management</span>
                    <span class="skyblue-txt body-txt">The ability to work in a team</span>
                </div>
            </div>
        </div>

        <!-- section experiences -->
        <div class="flex-container column-style" id="experiences">
            <div class="flex-container" id="exp-title">
                <span class="title">Volunteering and Working Experiences</span>
            </div>
            <div class="flex-container column-style" id="item-mainbox">
                <div class="flex-container item-box left-column column-style">
                    <span class="blue-txt body-txt">
                        Teaching Assistant of Programming Foundations 1 | Sep 2019 - Present
                    </span>
                    <span class="item-txt miring">
                        Faculty of Computer Science, University of Indonesia
                    </span>
                    <span class="sub-item">
                            I’m helping the lecturer tutoring 14 out of 58 students in lab session and 
                            teach them Python fundamentals and basic OOP using Python
                    </span>
                </div>
                <div class="flex-container item-box left-column column-style">
                    <span class="blue-txt body-txt">
                        Application Developer | June 2019 - Present
                    </span>
                    <span class="item-txt miring">
                        PT INOVASI INTI SUKSES - venation.io
                    </span>
                    <span class="sub-item">
                        Responsible for making web-based application (front-end & back-end) using 
                        Wordpress, ReactJS, Javascript, and other tools based on project
                    </span>
                </div>
                <div class="flex-container item-box left-column column-style">
                    <span class="blue-txt body-txt">
                        Staff of Business IT Case Competition | Mar 2019 - Sep 2019
                    </span>
                    <span class="item-txt miring">
                        COMPFEST XI
                    </span>
                    <span class="sub-item">
                        Manage the Business IT Competition held by COMPFEST XI, Faculty of Computer Science, University of Indonesia. 
                        I'm responsible to find jury and mentor for the competition.
                    </span>
                </div>
                <div class="flex-container item-box left-column column-style">
                    <span class="blue-txt body-txt">
                        Member of Sekolah BEM Fasilkom | Oct 2018 - Dec 2018
                    </span>
                    <span class="item-txt miring">
                        IT Bureau, Faculty of Computer Science, University of Indonesia
                    </span>
                    <span class="sub-item">
                        Learnt HTML, CSS, and Django framework fundamentals to make a simple portfolio website
                        including simple forms feature
                    </span>
                </div>                
            </div>
        </div>
        <!-- footer section -->
        <div class="flex-container footer">
            <span id="footer-txt">est. 2019 by Christopher Tamba</span>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

{% endblock %}

story3/templates/story3/my-projects.html
{% extends 'base_layout.html' %}

{% block content %}
{% load static %}
<body>
    <div id="project-page">
        <!-- projects section -->
        <div class="flex-container skyblue column-style" id="projects">
            <div class="flex-container" id="pro-title">
                <span class="title">My Projects</span>
            </div>
            <div class="flex-container row-style" id="pro-item">
                <div class="flex-container card" style="width: 18rem;" id="left-pro">
                    <img src="{% static 'img/imotion.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Imotion FEB UI Website</h5>
                        <p class="card-text">
                            A website that shows the competition's information with
                            simple registration page contains form for registering the
                            competition. This website was built using Wordpress.
                        </p>
                        <a href="https://imotionfebui.com/" class="btn btn-primary" target="_blank">Check it!</a>
                    </div>
                </div>
                <div class="flex-container card" style="width: 18rem;" id="right-pro">
                    <img src="{% static 'img/youtube.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">My Youtube Channel</h5>
                        <p class="card-text">
                            I enjoy creating a reaction video of some K-pop
                            Music Video. Kindly check my channel and subscibe it 
                            to support my channel.
                        </p>
                        <a href="https://www.youtube.com/channel/UCkvXFfg6ZeSCh-yjyYqieOA" class="btn btn-primary" target="_blank">
                            Check it!
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- footer section -->
        <div class="flex-container footer">
            <span id="footer-txt">est. 2019 by Christopher Tamba</span>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="#">
    <title>Christopher</title>
</head>

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="navigation">
    <div id="left-nav">
        <a class="navbar-brand" href="{% url 'story3:homepage' %}#intro" id="foto-kecil">
            <img src="{% static 'img/nav-photo.png' %}" alt="" id="foto-kecil">
        </a>
        <a class="navbar-brand " href="https://www.linkedin.com/in/christamba11/" target="_blank">
            <img src="{% static 'img/linkedIn.png' %}" alt="" class="ikon" id="">
        </a>
        <a class="navbar-brand" href="mailto:christamba11@gmail.com" target="_blank">
            <img src="{% static 'img/mail.png' %}" alt="" id="" class="ikon">
        </a>
        <a class="navbar-brand" href="https://www.instagram.com/christamba11/" target="_blank">
            <img src="{% static 'img/instagram.png' %}" alt="" id="" class="ikon">
        </a>
    </div>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon" id="tombol-nav"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link txt-ikon" href="{% url 'story3:homepage' %}#about">About <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link txt-ikon" href="{% url 'story3:homepage' %}#skills">Skills</a>
            <a class="nav-item nav-link txt-ikon" href="{% url 'story3:homepage' %}#experiences">Experiences</a>
            <a class="nav-item nav-link txt-ikon" href="{% url 'story3:projects' %}">Projects</a>
        </div>
    </div>
</nav>

{% block content %}



{% endblock %}
</html>